# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('gross', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('imdb_url', models.CharField(max_length=2000)),
                ('trailer_url', models.CharField(max_length=2000)),
                ('length', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
            ],
        ),
    ]
